# Generated by Django 5.0.7 on 2024-07-26 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_perfil_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='addressOne',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='addressTwo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='city',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='email',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='firstName',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='lastName',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='password',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='phoneOne',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='phoneTwo',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='state',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='username',
        ),
        migrations.RemoveField(
            model_name='perfil',
            name='zipCode',
        ),
    ]
