# Generated by Django 5.0.7 on 2024-07-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_profile_email_remove_profile_password_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='firstName',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='lastName',
            field=models.CharField(max_length=100),
        ),
    ]
