# Generated by Django 5.0.7 on 2024-08-06 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0001_initial'),
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='main_crud.order'),
        ),
    ]
