# Generated by Django 5.0.7 on 2024-08-15 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='photos_returned',
            field=models.CharField(verbose_name='Assets to be returned'),
        ),
    ]
