# Generated by Django 5.0.7 on 2024-08-12 22:57

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='selected_service',
        ),
        migrations.AddField(
            model_name='orderimage',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('Drone', 'Drone'), ('Photo', 'Photo'), ('3d scan', '3d scan'), ('Vídeo', 'Vídeo'), ('Floor Plan', 'Floor Plan')], max_length=36),
        ),
    ]
