# Generated by Django 5.0.7 on 2024-08-12 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_remove_orderimage_selected_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='photos_returned',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='photos_sent',
            field=models.IntegerField(),
        ),
    ]
