# Generated by Django 5.0.7 on 2024-08-07 12:18

import pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_alter_orderimage_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='editor_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.FileField(upload_to=pictures.models.order_image_path),
        ),
    ]
