# Generated by Django 5.0.7 on 2024-08-07 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_useraction'),
    ]

    operations = [
        migrations.RenameField(
            model_name='useraction',
            old_name='timestamp',
            new_name='action_date',
        ),
    ]
