# Generated by Django 5.0.7 on 2024-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_alter_orderimage_photos_returned_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='photos_returned',
            field=models.CharField(verbose_name='Assets to be uploaded'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='photos_sent',
            field=models.CharField(verbose_name='Assets to be uploaded'),
        ),
        migrations.AlterField(
            model_name='orderimage',
            name='scan_url',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
