# Generated by Django 5.0.7 on 2024-08-17 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_orderimage_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='preview_image',
        ),
    ]
