# Generated by Django 5.0.7 on 2024-08-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0005_remove_orderimage_preview_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='preview_image',
            field=models.ImageField(blank=True, null=True, upload_to='previews/'),
        ),
    ]
