# Generated by Django 5.0.7 on 2024-08-17 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0006_orderimage_preview_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='preview_image',
        ),
        migrations.AddField(
            model_name='orderimage',
            name='converted_image',
            field=models.ImageField(blank=True, null=True, upload_to='converted_images/'),
        ),
    ]
