# Generated by Django 5.0.7 on 2024-08-17 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0007_remove_orderimage_preview_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='converted_image',
        ),
    ]
