# Generated by Django 5.0.7 on 2024-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0008_remove_orderimage_converted_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='converted_image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
