# Generated by Django 5.0.7 on 2024-08-17 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0009_orderimage_converted_image_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='converted_image_path',
            field=models.ImageField(blank=True, null=True, upload_to='converted_images/'),
        ),
    ]
