# Generated by Django 5.0.7 on 2024-08-17 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0010_alter_orderimage_converted_image_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderimage',
            old_name='converted_image_path',
            new_name='converted_image',
        ),
    ]
