# Generated by Django 5.0.7 on 2024-09-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimage',
            name='selected_for_exclusion',
            field=models.BooleanField(default=False),
        ),
    ]
