# Generated by Django 5.0.7 on 2024-08-24 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimagegroup',
            name='zip_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
