# Generated by Django 5.0.7 on 2024-08-21 14:59

import apps.pictures.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='image',
            field=models.FileField(max_length=255, upload_to=apps.pictures.models.order_image_path),
        ),
    ]
