# Generated by Django 5.0.7 on 2024-09-24 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0003_orderimage_selected_for_exclusion'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderimagegroup',
            name='all_converted',
            field=models.BooleanField(default=False),
        ),
    ]
