# Generated by Django 5.0.7 on 2024-09-26 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pictures', '0004_orderimagegroup_all_converted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderimage',
            name='converted_image',
            field=models.ImageField(blank=True, max_length=500, null=True, upload_to='converted_images/'),
        ),
    ]
