# Generated by Django 5.0.7 on 2024-07-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreateOrders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('addressOne', models.CharField(max_length=150, verbose_name='Address 1')),
                ('AddressTwo', models.CharField(max_length=150, verbose_name='Address 2')),
                ('ZipCode', models.CharField(max_length=50, verbose_name='Zip Code')),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('services', models.CharField(max_length=300)),
            ],
        ),
    ]
