# Generated by Django 5.0.7 on 2024-08-13 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.CharField(max_length=150, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_created_at',
            field=models.CharField(max_length=150, verbose_name='Created At'),
        ),
    ]
