# Generated by Django 5.0.7 on 2024-07-30 01:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(help_text='MM/DD/YY')),
                ('time', models.TimeField(help_text='Ex: 3:00 to AM or 15:00 to PM')),
                ('addressOne', models.CharField(max_length=150, verbose_name='Address 1')),
                ('addressTwo', models.CharField(blank=True, max_length=150, null=True, verbose_name='Address 2')),
                ('zipCode', models.CharField(blank=True, max_length=50, null=True, verbose_name='Zip Code')),
                ('city', models.CharField(help_text='Ex: San Francisco', max_length=50)),
                ('state', models.CharField(help_text='Ex: CA', max_length=50)),
                ('services', models.CharField(help_text='Ex: Drone; Vídeos; Photos;', max_length=300)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='CreateOrders',
        ),
    ]
