# Generated by Django 5.0.7 on 2024-07-25 12:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='createorders',
            old_name='AddressTwo',
            new_name='addressTwo',
        ),
        migrations.RenameField(
            model_name='createorders',
            old_name='ZipCode',
            new_name='zipCode',
        ),
        migrations.AddField(
            model_name='createorders',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
