# Generated by Django 5.0.7 on 2024-08-03 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled',
            field=models.DateField(null=True, verbose_name='Scheduled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
