# Generated by Django 5.0.7 on 2024-08-16 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateTimeField(null=True, verbose_name='Scheduled'),
        ),
    ]
