# Generated by Django 5.0.7 on 2024-07-25 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0002_rename_addresstwo_createorders_addresstwo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createorders',
            name='user',
        ),
    ]
