# Generated by Django 5.0.7 on 2024-08-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0002_alter_order_appointment_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_team_members',
            field=models.CharField(verbose_name='Appointment Team Members'),
        ),
    ]
