# Generated by Django 5.0.7 on 2024-07-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0002_orders_delete_createorders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='orders',
            name='time',
            field=models.TimeField(),
        ),
    ]
