# Generated by Django 5.0.7 on 2024-08-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0003_alter_orders_date_alter_orders_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='services',
            field=models.CharField(choices=[('Drone', 'Drone'), ('Photo', 'Photo'), ('3d scan', '3d scan'), ('Vídeo', 'Vídeo')]),
        ),
    ]
