# Generated by Django 5.0.7 on 2024-08-13 12:26

import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0003_alter_order_appointment_team_members'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.CharField(max_length=150, null=True, verbose_name='Appointment Date'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_items',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Drone', 'Drone'), ('Photo', 'Photo'), ('3d scan', '3d scan'), ('Vídeo', 'Vídeo'), ('Floor Plan', 'Floor Plan')], max_length=200, verbose_name='Appointment Items'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_team_members',
            field=models.CharField(max_length=300, verbose_name='Appointment Team Members'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer',
            field=models.CharField(max_length=200, verbose_name='Customer'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_created_at',
            field=models.CharField(max_length=150, verbose_name='Created At'),
        ),
    ]
