# Generated by Django 5.0.7 on 2024-07-25 12:49

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0004_createorders_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CreateOrders',
            new_name='Orders',
        ),
    ]
