# Generated by Django 5.0.7 on 2024-08-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0004_alter_order_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.DateTimeField(null=True, verbose_name='Scheduled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_items',
            field=models.CharField(max_length=200, verbose_name='Services'),
        ),
        migrations.AlterField(
            model_name='order',
            name='appointment_team_members',
            field=models.CharField(max_length=300, verbose_name='Appointment Member'),
        ),
    ]
