# Generated by Django 5.0.7 on 2024-08-03 20:23

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0006_rename_orders_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Drone', 'Drone'), ('Photo', 'Photo'), ('3d scan', '3d scan'), ('Vídeo', 'Vídeo')], max_length=25),
        ),
    ]
