# Generated by Django 5.0.7 on 2024-08-13 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0006_alter_order_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_created_at',
            field=models.DateTimeField(auto_created=True, editable=False, verbose_name='Created At'),
        ),
    ]
