# Generated by Django 5.0.7 on 2024-08-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0007_alter_order_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='appointment_date',
            field=models.CharField(null=True, verbose_name='Scheduled'),
        ),
    ]
