# Generated by Django 5.0.7 on 2024-08-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0008_alter_order_appointment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_created_at',
            field=models.CharField(editable=False, verbose_name='Created At'),
        ),
    ]
