# Generated by Django 5.0.7 on 2024-09-04 23:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main_crud', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='ordereditorassignment',
            name='assigned_editor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordereditorassignment',
            name='order',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='main_crud.order'),
        ),
    ]
