# Generated by Django 5.0.7 on 2024-09-04 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_crud', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_status',
            field=models.CharField(choices=[('Not Uploaded', 'Not Uploaded'), ('Uploaded', 'Uploaded'), ('Production', 'Production'), ('Completed', 'Completed')], default='Not Uploaded', max_length=150, verbose_name='Status'),
        ),
    ]
